<project name="TEST_COOKIELOWPOWER" version="1.1">
    <ProjectDirectory>
        C:\Users\Victor Ros\Documents\Cookies\wake_up_radio\auxpoyect\TEST_COOKIELOWPOWER
    </ProjectDirectory>
    <View>
        SingleSTAPLView
    </View>
    <LogFile>
        C:\Users\Victor Ros\Documents\Cookies\wake_up_radio\auxpoyect\TEST_COOKIELOWPOWER\TEST_COOKIELOWPOWER.log
    </LogFile>
    <SerializationOption>
        Skip
    </SerializationOption>
    <configuration>
        <Hardware>
            <FlashPro>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
                <Vddl/>
                <Vdd>
2500                </Vdd>
            </FlashPro>
            <FlashProLite>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
            </FlashProLite>
            <FlashPro3>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro3>
            <FlashPro4>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro4>
        </Hardware>
        <Algo type="unknown">
            <irlength>
                0
            </irlength>
            <MaxTCK>
                4000000
            </MaxTCK>
        </Algo>
    </configuration>
</project>
