@TM:1352976746
@N:  :"":0:0:0:-1|Running in 32-bit mode
@TM:1352981562
@N: FP130 :"":0:0:0:-1|Promoting Net Y on CLKINT  I_73 
@TM:1352976749
@N: FP130 :"":0:0:0:-1|Promoting Net clk_c on CLKBUF  clk_pad 
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@W: MT420 :"":0:0:0:-1|Found inferred clock WuPu|clk with period 10.00ns. A user-defined clock should be declared on object "p:clk"
@TM:1352976746
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":13:10:13:13|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":1379:10:1379:13|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":1667:10:1667:13|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":1787:10:1787:12|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":1793:10:1793:14|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":1934:10:1934:12|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":2722:10:2722:12|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":2858:10:2858:15|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":3669:10:3669:15|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":3843:10:3843:17|M
@N: CD720 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\vhd\std.vhd":123:18:123:21|M
@N:  :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\component\work\WuPu\WuPu.vhd":8:7:8:10|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\component\work\WuPu\WuPu.vhd":8:7:8:10|M
@W: CL168 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\component\work\WuPu\WuPu.vhd":242:4:242:8|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\adressingData.vhd":12:7:12:20|M
@TM:1352976749
@N: BN116 :"c:\users\victor\documents\cookies\wake_up_radio\wuppmodbyirq\hdl\adressingdata.vhd":29:2:29:3|M
@TM:1352976746
@W: CL169 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\adressingData.vhd":29:2:29:3|M
@W: CL190 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\adressingData.vhd":29:2:29:3|M
@W: CL260 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\adressingData.vhd":29:2:29:3|M
@W: CL260 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\adressingData.vhd":29:2:29:3|M
@W: CD604 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\adressingData.vhd":51:4:51:17|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":17:7:17:21|M
@W: CL240 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":32:1:32:9|M
@N: CD231 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":40:16:40:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":54:7:54:22|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":55:7:55:20|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":71:7:71:21|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":73:7:73:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":77:7:77:15|M
@N: CL201 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":139:2:139:3|M
@W: CG296 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":146:20:146:26|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":149:20:149:24|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":223:29:223:39|M
@W: CG296 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":241:16:241:22|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":453:28:453:38|M
@TM:1352976749
@N:  :"c:\users\victor\documents\cookies\wake_up_radio\wuppmodbyirq\hdl\command_process_preamble.vhd":492:2:492:3|M
@TM:1352976746
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\freq_ref_preamble.vhd":8:7:8:14|M
@TM:1352976749
@N:  :"c:\users\victor\documents\cookies\wake_up_radio\wuppmodbyirq\hdl\freq_ref_preamble.vhd":28:8:28:9|M
@TM:1352976746
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\housekeepingCheck.vhd":8:7:8:23|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\manchester_encoder_preamble4WuR.vhd":12:7:12:24|M
@W: CL169 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\manchester_encoder_preamble4WuR.vhd":121:8:121:9|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\manchesterDecoder_preamble.vhd":19:7:19:11|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\manchesterDecoder_preamble.vhd":53:7:53:18|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\manchesterDecoder_preamble.vhd":60:7:60:15|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\manchesterDecoder_preamble.vhd":61:7:61:19|M
@TM:1352976749
@N:  :"c:\users\victor\documents\cookies\wake_up_radio\wuppmodbyirq\hdl\manchesterdecoder_preamble.vhd":245:1:245:2|M
@TM:1352976746
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Mom_unit_preamble.vhd":12:7:12:14|M
@N: CD231 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Mom_unit_preamble.vhd":62:16:62:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Mom_unit_preamble.vhd":81:7:81:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Mom_unit_preamble.vhd":94:7:94:16|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Mom_unit_preamble.vhd":111:7:111:18|M
@N: CL201 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Mom_unit_preamble.vhd":174:6:174:7|M
@W: CD434 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Mom_unit_preamble.vhd":184:77:184:85|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":7:7:7:15|M
@W: CL159 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":14:1:14:11|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":57:7:57:20|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":59:7:59:21|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":63:7:63:11|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":64:7:64:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":65:7:65:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":67:7:67:14|M
@W: CL240 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":67:7:67:14|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":70:7:70:18|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":72:7:72:11|M
@TM:1352978717
@N: CD233 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":88:16:88:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":91:7:91:16|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":92:7:92:14|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":93:7:93:15|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":94:7:94:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":95:7:95:19|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":96:7:96:22|M
@N: CL201 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":151:2:151:3|M
@W: CG296 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":162:20:162:26|M
@W: CD434 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":162:36:162:38|M
@W: CD434 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":162:68:162:75|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":184:7:184:19|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":184:31:184:46|M
@TM:1352981558
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":191:7:191:14|M
@W: CG296 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":199:16:199:22|M
@W: CD434 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":199:59:199:73|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":243:34:243:47|M
@TM:1352978717
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":268:6:268:18|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":268:30:268:45|M
@TM:1352976746
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\common\vhdl\FlashFreeze_Filter.vhd":7:7:7:24|M
@TM:1352976749
@N: BN116 :"c:\users\victor\documents\cookies\wake_up_radio\wuppmodbyirq\smartgen\common\vhdl\flashfreeze_filter.vhd":48:3:48:27|M
@N: BN116 :"c:\users\victor\documents\cookies\wake_up_radio\wuppmodbyirq\smartgen\common\vhdl\flashfreeze_filter.vhd":56:3:56:24|M
@W:  :"c:\users\victor\documents\cookies\wake_up_radio\wuppmodbyirq\smartgen\common\vhdl\flashfreeze_filter.vhd":64:3:64:23|M
@TM:1352976746
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\common\vhdl\FlashFreeze_FSM.vhd":6:7:6:21|M
@N: CD234 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\common\vhdl\FlashFreeze_FSM.vhd":43:16:43:17|M
@W: CD434 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\common\vhdl\FlashFreeze_FSM.vhd":52:12:52:23|M
@N: CL201 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\common\vhdl\FlashFreeze_FSM.vhd":63:6:63:7|M
@W: CD604 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\common\vhdl\FlashFreeze_FSM.vhd":130:12:130:25|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\common\vhdl\FlashFreeze_Managment.vhd":8:7:8:27|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\LowPowerManagement\LowPowerManagement.vhd":8:7:8:24|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\LowPowerManagement\LowPowerManagement_wrapper.vhd":35:7:35:32|M
