@TM:1358866202
@N:  :"":0:0:0:-1|Running in 32-bit mode
@N: FP130 :"":0:0:0:-1|Promoting Net RESETZB_c on CLKINT  I_58 
@N: FP130 :"":0:0:0:-1|Promoting Net clk_c on CLKBUF  clk_pad 
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@W: MT420 :"":0:0:0:-1|Found inferred clock WuPu|clk with period 100.00ns. A user-defined clock should be declared on object "p:clk"
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":13:10:13:13|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":37:10:37:13|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":1379:10:1379:13|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":1398:10:1398:15|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":1483:10:1483:17|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":1667:10:1667:13|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":1787:10:1787:12|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":1793:10:1793:14|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":1934:10:1934:12|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":2722:10:2722:12|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":2817:10:2817:13|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":2858:10:2858:15|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":3669:10:3669:15|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":3843:10:3843:17|M
@N: CD720 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\vhd\std.vhd":123:18:123:21|M
@N:  :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\component\work\WuPu\WuPu.vhd":8:7:8:10|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\component\work\WuPu\WuPu.vhd":8:7:8:10|M
@W: CL168 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\component\work\WuPu\WuPu.vhd":271:4:271:8|M
@W: CL168 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\component\work\WuPu\WuPu.vhd":274:4:274:8|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\adressingData.vhd":12:7:12:20|M
@N: BN116 :"c:\users\victor\documents\cookies\wake_up_radio\wuppmodbyirq\hdl\adressingdata.vhd":29:2:29:3|M
@W: CL169 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\adressingData.vhd":29:2:29:3|M
@W: CL190 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\adressingData.vhd":29:2:29:3|M
@W: CL260 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\adressingData.vhd":29:2:29:3|M
@W: CL260 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\adressingData.vhd":29:2:29:3|M
@W: CD604 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\adressingData.vhd":51:4:51:17|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":17:7:17:21|M
@W: CL159 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":21:1:21:11|M
@W: CL240 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":32:1:32:9|M
@N: CD231 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":40:16:40:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":55:7:55:22|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":56:7:56:20|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":62:7:62:20|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":82:7:82:21|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":84:7:84:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":88:7:88:15|M
@N: CL201 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":178:2:178:3|M
@W: CG296 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":185:20:185:26|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":188:20:188:24|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":258:28:258:43|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":267:29:267:39|M
@W: CG296 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":277:16:277:22|M
@W: CD434 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":277:56:277:68|M
@W: CD434 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":277:71:277:82|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":514:27:514:43|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":522:27:522:42|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":530:27:530:43|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":557:28:557:38|M
@N:  :"c:\users\victor\documents\cookies\wake_up_radio\wuppmodbyirq\hdl\command_process_preamble.vhd":601:2:601:3|M
@W: CL190 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":601:2:601:3|M
@W: CL260 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":601:2:601:3|M
@W: CL169 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":631:1:631:2|M
@W: CL169 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Command_Process_preamble.vhd":645:1:645:2|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\freq_ref_preamble.vhd":8:7:8:14|M
@N:  :"c:\users\victor\documents\cookies\wake_up_radio\wuppmodbyirq\hdl\freq_ref_preamble.vhd":28:8:28:9|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\housekeepingCheck.vhd":8:7:8:23|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\manchester_encoder_preamble4WuR.vhd":12:7:12:24|M
@W: CL169 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\manchester_encoder_preamble4WuR.vhd":122:8:122:9|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\manchesterDecoder_preamble.vhd":19:7:19:11|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\manchesterDecoder_preamble.vhd":55:7:55:18|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\manchesterDecoder_preamble.vhd":62:7:62:15|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\manchesterDecoder_preamble.vhd":63:7:63:19|M
@N:  :"c:\users\victor\documents\cookies\wake_up_radio\wuppmodbyirq\hdl\manchesterdecoder_preamble.vhd":266:1:266:2|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Mom_unit_preamble.vhd":12:7:12:14|M
@N: CD231 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Mom_unit_preamble.vhd":62:16:62:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Mom_unit_preamble.vhd":81:7:81:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Mom_unit_preamble.vhd":94:7:94:16|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Mom_unit_preamble.vhd":111:7:111:18|M
@N: CL201 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Mom_unit_preamble.vhd":174:6:174:7|M
@W: CD434 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\Mom_unit_preamble.vhd":184:77:184:85|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":7:7:7:15|M
@W: CL159 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":14:1:14:11|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":61:7:61:20|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":63:7:63:21|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":67:7:67:11|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":68:7:68:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":69:7:69:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":71:7:71:14|M
@W: CL240 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":71:7:71:14|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":74:7:74:18|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":76:7:76:11|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":87:7:87:16|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":88:7:88:16|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":89:7:89:15|M
@W: CL240 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":89:7:89:15|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":92:7:92:13|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":93:7:93:13|M
@N: CD233 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":96:16:96:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":99:7:99:16|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":100:7:100:14|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":101:7:101:15|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":102:7:102:17|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":103:7:103:19|M
@W: CD638 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":104:7:104:22|M
@N: CL201 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":142:2:142:3|M
@W: CG296 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":153:20:153:26|M
@W: CD434 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":153:36:153:38|M
@W: CD434 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":153:68:153:75|M
@W: CD434 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":153:110:153:118|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":171:10:171:15|M
@W: CG296 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":197:16:197:22|M
@W: CD434 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":197:59:197:73|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":241:34:241:47|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":266:6:266:18|M
@W: CG290 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\ZBControl_IRQs.vhd":266:30:266:45|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\common\vhdl\FlashFreeze_Filter.vhd":7:7:7:24|M
@N: BN116 :"c:\users\victor\documents\cookies\wake_up_radio\wuppmodbyirq\smartgen\common\vhdl\flashfreeze_filter.vhd":48:3:48:27|M
@N: BN116 :"c:\users\victor\documents\cookies\wake_up_radio\wuppmodbyirq\smartgen\common\vhdl\flashfreeze_filter.vhd":56:3:56:24|M
@W:  :"c:\users\victor\documents\cookies\wake_up_radio\wuppmodbyirq\smartgen\common\vhdl\flashfreeze_filter.vhd":64:3:64:23|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\common\vhdl\FlashFreeze_FSM.vhd":6:7:6:21|M
@N: CD234 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\common\vhdl\FlashFreeze_FSM.vhd":43:16:43:17|M
@W: CD434 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\common\vhdl\FlashFreeze_FSM.vhd":52:12:52:23|M
@N: CL201 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\common\vhdl\FlashFreeze_FSM.vhd":63:6:63:7|M
@W: CD604 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\common\vhdl\FlashFreeze_FSM.vhd":130:12:130:25|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\common\vhdl\FlashFreeze_Managment.vhd":8:7:8:27|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\LowPowerManagement\LowPowerManagement.vhd":8:7:8:24|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\LowPowerManagement\LowPowerManagement_wrapper.vhd":35:7:35:32|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\ZBWatchDog\ZBWatchDog.vhd":8:7:8:16|M
@W: CL168 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\ZBWatchDog\ZBWatchDog.vhd":148:4:148:13|M
@W: CL168 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\ZBWatchDog\ZBWatchDog.vhd":191:4:191:19|M
@W: CL168 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\ZBWatchDog\ZBWatchDog.vhd":195:4:195:14|M
@W: CL168 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\ZBWatchDog\ZBWatchDog.vhd":212:4:212:19|M
@W: CL168 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\smartgen\ZBWatchDog\ZBWatchDog.vhd":436:4:436:13|M
