@TM:1353577847
@N:  :"":0:0:0:-1|Running in 32-bit mode
@TM:1353577849
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@TM:1353577847
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":1996:10:1996:12|M
@N: CD630 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\igloo.vhd":2852:10:2852:13|M
@N: CD720 :"C:\Actel\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\vhd\std.vhd":123:18:123:21|M
@N:  :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\WaitTimeMx.vhd":8:7:8:16|M
@N: CD630 :"C:\Users\Victor\Documents\Cookies\wake_up_radio\WupPMODbyIRQ\hdl\WaitTimeMx.vhd":8:7:8:16|M
